[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter directories or open files via smart-enter"

[[input.prepend_keymap]]
on = "\u0012"  # Ctrl-r
run = "plugin smart-filter"
desc = "Filter entries with smart-filter"
