## Global zk config (read-only, provided by kakkle)

[note]
language = "en"
default-title = "Untitled"
filename = "{{id}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 4
id-case = "lower"

[format.markdown]
hashtags = true
colon-tags = true

[tool]
pager = "less -FIRX"
fzf-preview = "bat -p --color always {-1}"

[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"

[alias]

# Edit the last modified note
el = "zk edit --limit 1 --sort modified- $@"

# List note paths
paths = "zk list --format \"'{{path}}'\" --quiet --delimiter ' ' $@"

# Edit the notes selected interactively among the notes created the last two weeks
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
